name: SonarQube Issue Conversion
description: Transform tool output into generic SonarQube format(s)
inputs:
  input:
    description: Single or multiple tool output files to convert
    required: true
  output:
    description: Output file for converted issues
    required: true
  transformation:
    description: Type of transformation to apply (one of gtest-to-generic-execution, mutation-test-to-generic-issue)
    required: true

runs:
  using: composite
  steps:
    - uses: actions/setup-python@83679a892e2d95755f2dac6acb0bfd1e9ac5d548 # v6.1.0
      with:
        python-version: "3.13"

    - if: runner.os == 'Windows'
      shell: powershell
      env:
        INPUT: ${{ inputs.input }}
        OUTPUT: ${{ inputs.output }}
        TRANSFORMATION: ${{ inputs.transformation }}
      run: |
        python -m pip install -r $env:GITHUB_ACTION_PATH/requirements.txt
        python $env:GITHUB_ACTION_PATH/issue-converter.py

    - if: runner.os != 'Windows'
      shell: bash
      env:
        INPUT: ${{ inputs.input }}
        OUTPUT: ${{ inputs.output }}
        TRANSFORMATION: ${{ inputs.transformation }}
      run: |
        python -m pip install -r $GITHUB_ACTION_PATH/requirements.txt
        python $GITHUB_ACTION_PATH/issue-converter.py
