#!/usr/bin/env python

from lxml import etree
import sys

def open_etree(f):
    with open(f) as fd:
        parser = etree.XMLParser()
        return etree.parse(fd, parser)

if __name__ == "__main__":
    transformer = etree.XSLT(open_etree(sys.argv[1]))
    for f in sys.argv[2:]:
        sys.stdout.write(str(transformer(open_etree(f))))
