---
name: Finalize Release

permissions:
  contents: read

on:
  release:
    types: [published]

jobs:
  comment-released-prs:
    name: Comment on released PRs
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - uses: rdlf0/comment-released-prs-action@249f57bed533baa7f883fe9d9a834424f153c3cb # v3.2.0
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
